---
# Exclude all files in the template directory, as these are not well formed due
# to the template strings.
exclude: "^{{.*"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter and automatically fix violations when possible.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
